// This will be generated by swagger-typescript-api
export const createFetchInstance = (config: { baseUrl: string }) => {
  return {
    baseUrl: config.baseUrl,
    get: (url: string) => fetch(`${config.baseUrl}${url}`).then(r => r.json()),
    post: (url: string, data: any) => fetch(`${config.baseUrl}${url}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data)
    }).then(r => r.json())
  };
};
