services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: cm
      POSTGRES_PASSWORD: cm
      POSTGRES_DB: cmdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
