name: CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
       
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm --filter apps/api build
      - run: curl http://localhost:4000/docs-json > packages/api-sdk/openapi.json || true
      - run: pnpm --filter @api-sdk/client generate
      - run: pnpm build
